=== apple-x-co/bear-app/source/app/env.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "ADMIN_BASE_URL": {
      "type": "string",
      "description": "System administrator CMS base url",
      "format": "uri"
    },
    "ADMIN_EMAIL_ADDRESS": {
      "type": "string",
      "description": "System administrator notification email address"
    },
    "ADMIN_STATIC_BASE_URL": {
      "type": "string",
      "description": "System administrator CMS base url",
      "format": "uri"
    },
    "CLOUDFLARE_TURNSTILE_SECRET_KEY": {
      "type": "string",
      "description": "Cloudflare Turnstile secret key"
    },
    "CLOUDFLARE_TURNSTILE_SITE_KEY": {
      "type": "string",
      "description": "Cloudflare Turnstile site key"
    },
    "DB_DSN": {
      "type": "string",
      "description": "Database name",
      "minLength": 1,
      "default": "mysql:host=${DB_HOST};dbname=${DB_NAME};charset=utf8mb4"
    },
    "DB_USER": {
      "type": "string",
      "description": "Database connected user name",
      "minLength": 1
    },
    "DB_PASS": {
      "type": "string",
      "description": "Database connected user password",
      "minLength": 1
    },
    "DB_SLAVE": {
      "type": "string",
      "description": "Database slave hosts",
      "default": ""
    },
    "ENCRYPT_PASS": {
      "type": "string",
      "description": "Encrypter passphrase.",
      "minLength": 16,
      "maxLength": 16
    },
    "LANG_OVERRIDE_DIR": {
      "type": "string",
      "description": "Language override directory relative path",
      "default": ""
    },
    "PUBLIC_BASE_URL": {
      "type": "string",
      "description": "Public base url",
      "format": "uri"
    },
    "PUBLIC_STATIC_BASE_URL": {
      "type": "string",
      "description": "Public base url",
      "format": "uri"
    },
    "SERVICE_NAME": {
      "type": "string",
      "description": "Service name"
    },
    "SMTP_HOST":  {
      "type": "string",
      "description": "SMTP server to send through",
      "minLength": 1
    },
    "SMTP_PORT": {
      "type": "string",
      "description": "TCP port to connect to"
    },
    "SMTP_USER": {
      "type": "string",
      "description": "SMTP username",
      "minLength": 1
    },
    "SMTP_PASS": {
      "type": "string",
      "description": "SMTP password",
      "minLength": 1
    },
    "SMTP_OPTION": {
      "type": "string",
      "description": "SMTP OPTION"
    }
  },
  "required": [
    "ADMIN_BASE_URL",
    "ADMIN_EMAIL_ADDRESS",
    "ADMIN_STATIC_BASE_URL",
    "CLOUDFLARE_TURNSTILE_SECRET_KEY",
    "CLOUDFLARE_TURNSTILE_SITE_KEY",
    "DB_DSN",
    "DB_USER",
    "DB_PASS",
    "ENCRYPT_PASS",
    "SERVICE_NAME",
    "PUBLIC_BASE_URL",
    "PUBLIC_STATIC_BASE_URL",
    "SMTP_HOST",
    "SMTP_PORT",
    "SMTP_USER",
    "SMTP_PASS",
    "SMTP_OPTION"
  ]
}

=== apple-x-co/bear-app/source/app/env.dist.json
{
  "$schema" : "./env.schema.json",
  "ADMIN_BASE_URL": "https://example.com",
  "ADMIN_EMAIL_ADDRESS" : "admin@example.com",
  "ADMIN_STATIC_BASE_URL": "https://example.com/admin-dist",
  "CLOUDFLARE_TURNSTILE_SECRET_KEY": "DUMMY",
  "CLOUDFLARE_TURNSTILE_SITE_KEY": "DUMMY",
  "DB_DSN" : "mysql:host=localhost:3306;dbname=DUMMY;charset=utf8mb4",
  "DB_PASS" : "DUMMY",
  "DB_USER" : "DUMMY",
  "ENCRYPT_PASS" : "abcdefghijklmnop",
  "PUBLIC_BASE_URL": "https://example.com",
  "PUBLIC_STATIC_BASE_URL": "https://example.com/public-dist",
  "SMTP_HOST" : "DUMMY",
  "SMTP_OPTION" : "",
  "SMTP_PASS" : "DUMMY",
  "SMTP_PORT" : "465",
  "SMTP_USER" : "DUMMY",
  "SERVICE_NAME": "DUMMY"
}
